#
#  mmmm mmmmmmm m    m mmmmm 
# #"   "   #    #    # #    #
# "#mmm    #    #    # #mmmm"
#     "#   #    #    # #    #
# "mmm#"   #    "mmmm" #mmmm"
#

FROM debian:trixie-slim

RUN date | tee /date
